---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

- name: 1.8 - Apt upgrade
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt
    - CIS_1.8
  notify:
    - Reboot host


