---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

#- name: 4.3 - Check log rotate
#  stat: path=/etc/logrotate.conf
#  register: logrotate
#  tags:
#    - CIS_4.3
#    - CIS_4.3.1

- name: 5.4.1.1-3 - Set password expiration, minimum age & warning age.
  lineinfile:
    path: /etc/login.defs
#    create: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
   - { regexp: 'PASS_MAX_DAYS',  line: 'PASS_MAX_DAYS   365'  }
   - { regexp: 'PASS_MIN_DAYS',  line: 'PASS_MIN_DAYS   7'  }
   - { regexp: 'PASS_WARN_AGE',  line: 'PASS_WARN_AGE   7'  }
  notify:
#    - Reboot host
  tags:
    - CIS_5.4.1
    - CIS_5.4.1.1
    - CIS_5.4.1.2
    - CIS_5.4.1.3

- name: 5.4.1.4 - Set default inactive time
  shell: "/usr/sbin/useradd -D -f 30"
  tags:
    - CIS_5.4.1.4

- name: 5.4.2 - Script to lock service accounts local login
  template:
    src: lock-service-accounts.sh.j2
    dest: ~/lock-service-accounts.sh
    mode: u+x
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - never
    - CIS_5.4.2

- name: 5.4.2 - Run script to lock user accounts
  shell:
    cmd: ~/lock-service-accounts.sh
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - never
    - CIS_5.4.2

- name: 5.4.3 - Set root default group to GID 0
  shell:
    cmd: usermod -g 0 root
#  become: yes
#  become_user: "{{ ansible_user }}"
  tags:
    - never
    - CIS_5.4.3

- name: 5.4.4 - Set bash umask to 027
  lineinfile:
    path: "{{ item.path }}"
#    create: yes
    regexp: 'umask 027'
    line: 'umask 027'
  with_items:
   - { path: '/etc/bash.bashrc' }
   - { path: '/etc/profile' }
# The above two files set the umask value globally, review if this should be set also.
# If so, you need to call out all of the .sh files individually, or scan the folder and return a list.
#   - { path: /etc/profile.d/*.sh }
  notify:
#    - Reboot host
  tags:
    - CIS_5.4.4

- name: 5.4.5 - Set bash timeout
  lineinfile:
    path: "{{ item.path }}"
#    create: yes
    regexp: '^TMOUT'
    line: 'TMOUT=600'
  with_items:
   - { path: '/etc/bash.bashrc' }
   - { path: '/etc/profile' }
# The above two files set the TMOUT value globally, review if this should be set also.
# If so, you need to call out all of the .sh files individually, or scan the folder and return a list.
#   - { path: /etc/profile.d/*.sh }
  notify:
#    - Reboot host
  tags:
    - CIS_5.4.5

