---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

# Disabling Wireless is not relevant for VMs
- name: 4.1.1.1 - Set log file size
  apt:
    name: aide, aide-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - CIS_4.1.1
    - CIS_4.1.1.1


- name: 4.1.1.1 - Set log file size
  lineinfile:
    dest: /etc/audit/auditd.conf
    state: present
    backup: yes
    create: yes
    owner: root
    group: root
    mode: 0644
    regexp: 'install sctp \/bin\/true'
    line: 'install sctp /bin/true'
  tags:
    - CIS_3.5.2
  notify:
    - Reboot host