---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

# Disabling Wireless is not relevant for VMs
- name: 3.7.1 - Disabling Wireless is not relevant for VMs
  stat: path=/etc/netplan/50-cloud-init.yaml
  register: disable_wireless
  tags:
    - CIS_3.7.1
