---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

- name: 2.3.x - Remove clients (nis, rsh-client, rsh-redone-client, talk, ldap-utils)
  apt:
    name: nis, rsh-client, rsh-redone-client, talk, ldap-utils
    state: absent
  tags:
    - services
    - CIS_2.3.1
    - CIS_2.3.2
    - CIS_2.3.3
    - CIS_2.3.4
    - CIS_2.3.5

