---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

- name: 1.7.1.4 - Set /etc/motd based on template
  template:
    src: etc_motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags:
    - MOTD
    - CIS_1.7.1
    - CIS_1.7.1.4

- name: 1.7.1.5 - Set /etc/issue based on template
  template:
    src: etc_issue.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags:
    - MOTD
    - CIS_1.7.1
    - CIS_1.7.1.5

- name: 1.7.1.6 - Set /etc/issue.net based on template
  template:
    src: etc_issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags:
    - MOTD
    - CIS_1.7.1
    - CIS_1.7.1.6

- name: 1.7.1.1 - Remove \v \r \m \s from /etc/motd
  replace:
    path: /etc/motd
#    state: absent
    regexp: '(?i)\\v|\\r|\\m|\\s'
    replace: ""
    backup: yes
  tags:
    - MOTD
    - CIS_1.7.1
    - CIS_1.7.1.1

- name: 1.7.1.2 - Remove \v \r \m \s from /etc/issue
  replace:
    path: /etc/issue
#    state: absent
    regexp: '(?i)\\v|\\r|\\m|\\s'
    replace: ""
    backup: yes
  tags:
    - MOTD
    - CIS_1.7.1
    - CIS_1.7.1.2

- name: 1.7.1.3 - Remove \v \r \m \s from /etc/issue.net
  replace:
    path: /etc/issue.net
#    state: absent
    regexp: '(?i)\\v|\\r|\\m|\\s'
    replace: ""
    backup: yes
  tags:
    - MOTD
    - CIS_1.7.1
    - CIS_1.7.1.3

# 1.7.2 No GUI, CLI access to ubuntu servers only

- name: 1.7.2 - Check for /etc/gdm3/
  stat: path=/etc/gdm3
  register: gdm3_greeter
  tags:
    - CIS_1.7.2

- name: 1.7.2 - Place /etc/gdm3/greeter.dconf-defaults
  template:
    src: etc_gdm3_greeter.dconf-defaults.j2
    dest: /etc/gdm3/greeter.dconf-defaults
    owner: root
    group: root
    mode: '0644'
  when: gdm3_greeter.stat.exists
  tags:
    - CIS_1.7.2
