---
# This playbook for CIS Ubuntu 18.04 hardening

- name: Apply CIS 1.1
  hosts: all
  become: yes
  roles:
    - CIS_1.1
  tags:
    - CIS_1.1

- name: Apply CIS 1.2
  hosts: all
  become: yes
  roles:
    - CIS_1.2
  tags:
    - CIS_1.2

- name: Apply CIS 1.3
  hosts: all
  become: yes
  roles:
    - CIS_1.3
  tags:
    - CIS_1.3

- name: Apply CIS 1.4
  hosts: all
  become: yes
  roles:
    - CIS_1.4
  tags:
    - CIS_1.4

- name: Apply CIS 1.5
  hosts: all
  become: yes
  roles:
    - CIS_1.5
  tags:
    - CIS_1.5

- name: Apply CIS 1.6
  hosts: all
  become: yes
  roles:
    - CIS_1.6
  tags:
    - CIS_1.6

- name: Apply CIS 1.7
  hosts: all
  become: yes
  roles:
    - CIS_1.7
  tags:
    - CIS_1.7

- name: Apply CIS 1.8
  hosts: all
  become: yes
  roles:
    - CIS_1.8
  tags:
    - CIS_1.8


