---
# This playbook for CIS Ubuntu 18.04 hardening


- name: Apply CIS 5.1
  hosts: all
  become: yes
  roles:
    - CIS_5.1
  tags:
    - CIS_5.1

- name: Apply CIS 5.2
  hosts: all
  become: yes
  roles:
    - CIS_5.2
  tags:
    - CIS_5.2

- name: Apply CIS 5.3
  hosts: all
  become: yes
  roles:
    - CIS_5.3
  tags:
    - CIS_5.3
