---
# This playbook for CIS Ubuntu 18.04 hardening


- name: Apply CIS 5.1
  hosts: all
  roles:
    - CIS_5.1
  become: yes
  tags:
    - CIS_5.1

- name: Apply CIS 5.2
  hosts: all
  roles:
    - CIS_5.2
  become: yes
  tags:
    - CIS_5.2
