---
# This playbook for CIS Ubuntu 18.04 hardening

#- name: load variables
#  include_vars:
#    file: global.yml


#- name: Apply CIS 4.1
- name: Skipping 4.1 because it's all L2
  hosts: all
  become: yes
  roles:
#    - CIS_4.1
  become: yes
  tags:
    - CIS_4.1

- name: Apply CIS 4.2
  hosts: all
  become: yes
  roles:
    - CIS_4.2
  tags:
    - CIS_4.2
