---
# This playbook is for my stuff

- name: Apply user config
  hosts: all
  roles:
    - user
  become: yes
  tags:
    - never
    - user
#
#- name: Apply common config
#  hosts: all
#  roles:
#    - common
#  become: yes

