---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

- name: 5.1.1 - Enable cron
  systemd:
    state: restarted
    name: cron
  notify:
    - Restart cron
  tags:
    - CIS_5.1.1


- name: 5.1.2-8 - Set cron file permissions
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: touch
    owner: root
    group: root
  with_items:
    - { path: '/etc/crontab',      mode: '0600' }
    - { path: '/etc/cron.hourly',  mode: '0700' }
    - { path: '/etc/cron.daily',   mode: '0700' }
    - { path: '/etc/cron.weekly',  mode: '0700' }
    - { path: '/etc/cron.monthly', mode: '0700' }
    - { path: '/etc/cron.d',       mode: '0700' }
    - { path: '/etc/cron.allow',   mode: '0600' }
    - { path: '/etc/at.allow',     mode: '0600' }
  notify:
    - Restart cron
  tags:
    - CIS_5.1.2
    - CIS_5.1.3
    - CIS_5.1.4
    - CIS_5.1.5
    - CIS_5.1.6
    - CIS_5.1.7
    - CIS_5.1.8

- name: 5.1.8 - Remove /etc/cron.deny & /etc/at.deny
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - { path: '/etc/cron.deny' }
    - { path: '/etc/at.deny' }
  notify:
    - Restart cron
  tags:
    - CIS_5.1.8
