---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

- name: 5.3.1 - Install libpam-pwquality
  apt:
    name: libpam-pwquality
    state: present
  tags:
    - CIS_5.3.1
  notify:
    - Restart pam.d

- name: 5.3.1 - pam.d settings, password requirements '/etc/security/pwquality.conf'
  lineinfile:
    path: /etc/security/pwquality.conf
    create: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
   - { regexp: 'minlen',  line: 'minlen = 14'  }
   - { regexp: 'dcredit', line: 'dcredit = -1' }
   - { regexp: 'ucredit', line: 'ucredit = -1' }
   - { regexp: 'ocredit', line: 'ocredit = -1' }
   - { regexp: 'lcredit', line: 'lcredit = -1' }
  notify:
#    - Reboot host
  tags:
    - CIS_5.3.1

- name: 5.3.1, 5.3.3 - pam.d settings, password retry '/etc/pam.d/common-password'
  lineinfile:
    path: /etc/pam.d/common-password
    create: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
   - { regexp: 'password[ \t]requisite[ \t]pam\_pwquality\.so',
      line: 'password requisite pam_pwquality.so retry=3'  }
   - { regexp: 'password[ \t]required[ \t]pam\_pwhistory\.so',
      line: 'password required pam_pwquality.so retry=3'  }
#   - { regexp: 'password[ \t]\[success\required[ \t]pam\_pwhistory\.so',
#      line: 'password required pam_pwquality.so retry=3'  }
  notify:
#    - Reboot host
  tags:
    - CIS_5.3.1
    - CIS_5.3.3
    - CIS_5.3.4

- name: 5.3.2 - pam.d settings, locker user id after failed logon attempts '/etc/pam.d/common-auth'
  lineinfile:
    path: /etc/pam.d/common-auth
    create: yes
    regexp: "{{ item.regexp }}"
    insertafter: "auth[ \t]required"
    line: "{{ item.line }}"
  with_items:
   - { regexp: 'auth[ \t]+required[ \t]pam\_tally2\.so',
      line: 'auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900'  }
  notify:
#    - Reboot host
  tags:
    - CIS_5.3.2
