---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

# Get keys from https://ftp-master.debian.org/keys/
- name: 1.4.1 - Set permissions on grub
  file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: '0400'
  tags:
    - boot
    - CIS_1.4.1
  notify:
    - Update Grub2 config file ubuntu
#    - Reboot host
  become: yes
  become_user: root


- name: 1.4.2 - Set grub password file
  template:
    src: etc_grub.d_50_custom.j2
    dest: /etc/grub.d/50_custom
    mode: '0755'
  tags:
    - boot
    - CIS_1.4.2
  notify:
    - Update Grub2 config file ubuntu
    - Reboot host
  become: yes
  become_user: root

# Allow system to auto boot
- name: 1.4.2 - Set grub menu entry --unrestricted
  lineinfile:
    dest: /etc/grub.d/10_linux
    state: present
    regexp: ^CLASS="--class gnu-linux --class gnu --class os"
    line: CLASS="--class gnu-linux --class gnu --class os --unrestricted"
  tags:
    - boot
  notify:
    - Reboot host
    - Update Grub2 config file ubuntu
  become: yes
  become_user: root

