---
# This playbook contains common handlers that can be called in "setup" tasks.

#handlers:

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
    enabled: yes

- name: Reboot host
  reboot:

