---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

# Get keys from https://ftp-master.debian.org/keys/
- name: 1.3.1 - Install AIDE
  apt:
    name: aide, aide-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - filesystem
    - CIS_1.3.1
  notify:
    - Reboot host

- name: 1.3.2 - Run AIDE as a crontab job
  lineinfile:
    path: /etc/crontab
    regexp: 'aide.wrapper'
    line: "0  5    * * *           /usr/bin/aide.wrapper --config /etc/aide/aide.conf --check"
    state: present
    backup: yes
    create: no
  tags:
    - filesystem
    - CIS_1.3.2
  notify:
    - Reboot host
