---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

- name: 1.1.1.1 - Disable cramfs
  lineinfile:
    path: /etc/modprobe.d/cramfs.conf
    regexp: 'install cramfs /bin/true'
    line: "install cramfs /bin/true"
    state: present
    backup: yes
    create: yes
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.1
  notify:
    - Reboot host

- name: 1.1.1.1 - unload cramfs
  modprobe:
    name: cramfs
    state: absent
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.1
  notify:
    - Reboot host

- name: 1.1.1.2 - Disable freevxfs
  lineinfile:
    path: /etc/modprobe.d/freevxfs.conf
    regexp: 'install freevxfs /bin/true'
    line: "install freevxfs /bin/true"
    state: present
    backup: yes
    create: yes
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.2
  notify:
    - Reboot host

- name: 1.1.1.2 - unload freevxfs
  modprobe:
    name: freevxfs
    state: absent
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.2
  notify:
    - Reboot host

- name: 1.1.1.3 - Disable jffs2
  lineinfile:
    path: /etc/modprobe.d/jffs2.conf
    regexp: 'install jffs2 /bin/true'
    line: "install jffs2 /bin/true"
    state: present
    backup: yes
    create: yes
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.3
  notify:
    - Reboot host

- name: 1.1.1.3 - unload jffs2
  modprobe:
    name: jffs2
    state: absent
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.3
  notify:
    - Reboot host

- name: 1.1.1.4 - Disable hfs
  lineinfile:
    path: /etc/modprobe.d/hfs.conf
    regexp: 'install hfs /bin/true'
    line: "install hfs /bin/true"
    state: present
    backup: yes
    create: yes
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.4
  notify:
    - Reboot host

- name: 1.1.1.4 - unload hfs
  modprobe:
    name: hfs
    state: absent
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.4
  notify:
    - Reboot host

- name: 1.1.1.5 - Disable hfsplus
  lineinfile:
    path: /etc/modprobe.d/hfsplus.conf
    regexp: 'install hfsplus /bin/true'
    line: "install hfsplus /bin/true"
    state: present
    backup: yes
    create: yes
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.5
  notify:
    - Reboot host

- name: 1.1.1.5 - unload hfsplus
  modprobe:
    name: hfsplus
    state: absent
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.5
  notify:
    - Reboot host

- name: 1.1.1.6 - Disable udf
  lineinfile:
    path: /etc/modprobe.d/udf.conf
    regexp: 'install udf /bin/true'
    line: "install udf /bin/true"
    state: present
    backup: yes
    create: yes
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.6
  notify:
    - Reboot host

- name: 1.1.1.6 - unload udf
  modprobe:
    name: udf
    state: absent
  tags:
    - filesystem
    - CIS_1.1.1
    - CIS_1.1.1.6
  notify:
    - Reboot host
