---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

- name: 4.3 - Check log rotate
  stat: path=/etc/logrotate.conf
  register: logrotate
  tags:
    - CIS_4.3
    - CIS_4.3.1

- name: 4.3.1 - Place logrotate.conf
  template:
    src: etc_logrotate.conf.j2
    dest: /etc/logrotate.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
#  when: logrotate.stat.exists
  tags:
    - CIS_4.3
    - CIS_4.3.1
