---
# This playbook contains Ubuntu 18.04LTS CIS benchmark v1.0.0 settings

- name: 3.1.1 - Disable IP forwarding
  lineinfile:
    dest: /etc/sysctl.conf
    state: present
    backup: yes
    regexp: '\#net\.ipv4\.ip\_forward'
    line: 'net.ipv4.ip_forward = 0'
  tags:
    - packet redirect
    - CIS_3.1.1
  notify:
    - Reboot host

- name: 3.1.2 - Disable Packet redirect 'net.ipv4.conf.all.send_redirects'
  lineinfile:
    dest: /etc/sysctl.conf
    state: present
    backup: yes
    regexp: 'net\.ipv4\.conf\.all\.send\_redirects'
    line: 'net.ipv4.conf.all.send_redirects = 0'
  tags:
    - packet redirect
    - CIS_3.1.2
  notify:
    - Reboot host

- name: 3.1.2 - Disable Packet redirect 'net.ipv4.conf.default.send_redirects'
  lineinfile:
    dest: /etc/sysctl.conf
    state: present
    backup: yes
    regexp: 'net\.ipv4\.conf\.default\.send\_redirects'
    insertafter: 'net\.ipv4\.conf\.all\.send\_redirects'
    line: 'net.ipv4.conf.default.send_redirects = 0'
  tags:
    - packet redirect
    - CIS_3.1.2
  notify:
    - Reboot host
