---
# This playbook contains common handlers that can be called in "setup" tasks.

#handlers:

- name: restart auditd
  systemd:
    name: auditd
    state: restart
    enabled: yes


- name: Reboot host
  reboot:

